version: '3.1'

services:
 
 uwsgi-nginx:
  build: ./docker-uwsgi-nginx
  image: nda86/u-nginx
  restart: always
  volumes:
   - "./app:/app"
  environment:
   LISTEN_PORT: 80
   NGINX_MAX_UPLOAD: "75m"
   NGINX_WORKER_PROCESS: 2
   NGINX_WORKER_CONNECTION: 1024
   NGINX_WORKER_OPEN_FILES: 2048
   STATIC_URL: "/static"
   STATIC_PATH: "/app/static"
   STATIC_INDEX: 0
   UWSGI_INI: "/app"
   UWSGI_CHEAPER: 2
   UWSGI_PROCESS: 16
   UWSGI_READ_TIMEOUT: 3600
   BASE_URL: http://192.168.75.128
  ports:
   - 80:80
  depends_on:
   - db

 db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: shorteit
  volumes:
  - "./dbdata:/var/lib/mysql"


 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080
  depends_on:
    - db

 redis:
  image: 'bitnami/redis:latest'
  environment:
   - ALLOW_EMPTY_PASSWORD=yes
