# Generated by Django 3.1.2 on 2020-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='user_id',
            field=models.UUIDField(verbose_name='Идентификатор пользователя'),
        ),
    ]
