# Generated by Django 3.1.2 on 2020-10-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201006_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(unique=True, verbose_name='Сокращенный URL'),
        ),
    ]
