version: 1

disable_exsisteng_loggers: False

formatters:
  std_format:
    format: "{asctime} - {module}.{funcName} - {levelname} - {message}"
    style: "{"

handlers:
  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: std_format
    filename: debug.log

  unhandled_exception_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: std_format
    filename: unhandled_exception.log


  django_log:
    class: logging.FileHandler
    level: INFO
    filename: django_debug.log

loggers:
  debug_log:
    level: DEBUG
    handlers: [debug_file_handler]

  unhandled_exception:
    level: ERROR
    handlers: [unhandled_exception_handler]

  django:
    handlers: [django_log]
    propogate: True
