# Generated by Django 3.1.2 on 2020-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='Идентификатор пользователя')),
                ('original_url', models.URLField(verbose_name='Оригинальный URL')),
                ('short_url', models.URLField(verbose_name='Сокращенный URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания короткого URL')),
                ('count_click', models.IntegerField(default=0, verbose_name='Количество переходов по короткому URL')),
            ],
        ),
    ]
